# Generated by Django 5.2.6 on 2025-09-23 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Покупатель', 'verbose_name_plural': 'Покупатели'},
        ),
        migrations.RemoveField(
            model_name='user',
            name='birth_date',
        ),
        migrations.RemoveField(
            model_name='user',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_phone_verified',
        ),
        migrations.RemoveField(
            model_name='user',
            name='receive_newsletters',
        ),
        migrations.RemoveField(
            model_name='user',
            name='receive_sms',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='company',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='middle_name',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='position',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='sms_orders',
        ),
        migrations.AddField(
            model_name='user',
            name='birth_day',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='День рождения'),
        ),
        migrations.AddField(
            model_name='user',
            name='birth_month',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Месяц рождения'),
        ),
        migrations.AddField(
            model_name='user',
            name='birth_year',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Год рождения'),
        ),
        migrations.AddField(
            model_name='user',
            name='middle_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='Отчество'),
        ),
        migrations.AddField(
            model_name='user',
            name='receive_congratulations',
            field=models.BooleanField(default=True, verbose_name='Получать поздравления'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=150, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=150, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='user',
            name='registration_source',
            field=models.CharField(choices=[('email', 'Email'), ('google', 'Google'), ('telegram', 'Telegram')], default='email', max_length=20, verbose_name='Источник регистрации'),
        ),
    ]
