# Generated by Django 5.2.6 on 2025-09-23 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_options_remove_user_birth_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.AddField(
            model_name='user',
            name='admin_role',
            field=models.CharField(blank=True, choices=[('super_admin', 'Супер администратор'), ('manager', 'Менеджер'), ('content_manager', 'Контент-менеджер'), ('support', 'Поддержка')], max_length=20, null=True, verbose_name='Роль администратора'),
        ),
        migrations.AddField(
            model_name='user',
            name='receive_notifications',
            field=models.BooleanField(default=True, verbose_name='Получать уведомления'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('customer', 'Покупатель'), ('admin', 'Администратор')], default='customer', max_length=20, verbose_name='Тип пользователя'),
        ),
    ]
