# Generated by Django 5.2.6 on 2025-09-29 10:48

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_options_user_admin_role_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminUser',
            fields=[
            ],
            options={
                'verbose_name': 'Администратор',
                'verbose_name_plural': 'Администраторы',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('users.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='CustomerUser',
            fields=[
            ],
            options={
                'verbose_name': 'Покупатель',
                'verbose_name_plural': 'Покупатели',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('users.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='birth_day',
        ),
        migrations.RemoveField(
            model_name='user',
            name='birth_month',
        ),
        migrations.RemoveField(
            model_name='user',
            name='birth_year',
        ),
        migrations.RemoveField(
            model_name='user',
            name='receive_congratulations',
        ),
        migrations.AddField(
            model_name='user',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата рождения'),
        ),
        migrations.AddField(
            model_name='user',
            name='country',
            field=models.CharField(default='Россия', max_length=100, verbose_name='Страна'),
        ),
        migrations.AddField(
            model_name='user',
            name='has_telegram_auth',
            field=models.BooleanField(default=False, verbose_name='Авторизация через Telegram'),
        ),
        migrations.AlterField(
            model_name='user',
            name='registration_source',
            field=models.CharField(choices=[('email', 'Email'), ('telegram', 'Telegram')], default='email', max_length=20, verbose_name='Источник регистрации'),
        ),
    ]
