# Generated by Django 5.2.6 on 2025-10-05 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_address_options_address_cdek_pvz_code_and_more'),
        ('users', '0005_alter_customeruser_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAddress',
            fields=[
            ],
            options={
                'verbose_name': 'Адрес доставки',
                'verbose_name_plural': 'Адреса доставки',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.address',),
        ),
    ]
