# Generated by Django 5.2.6 on 2025-09-29 11:37

import apps.core.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0002_initial'),
        ('core', '0003_alter_address_options_address_cdek_pvz_code_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('number', models.CharField(max_length=50, unique=True, verbose_name='Номер заказа')),
                ('user_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP пользователя')),
                ('source', models.CharField(blank=True, max_length=100, verbose_name='Источник перехода')),
                ('first_visit_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата первого визита')),
                ('status', models.CharField(choices=[('pending', 'Ожидает оплаты'), ('paid', 'Оплачен'), ('processing', 'В обработке'), ('shipped', 'Отправлен'), ('delivered', 'Доставлен'), ('cancelled', 'Отменен'), ('returned', 'Возвращен')], default='pending', max_length=20, verbose_name='Статус заказа')),
                ('order_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата заказа')),
                ('payment_method', models.CharField(choices=[('card', 'Банковская карта'), ('cash', 'Наличные'), ('transfer', 'Банковский перевод'), ('yookassa', 'ЮKassa')], max_length=50, verbose_name='Способ оплаты')),
                ('paid_amount', apps.core.models.MoneyField(decimal_places=2, max_digits=10, verbose_name='Оплаченная сумма')),
                ('export_status', models.CharField(choices=[('pending', 'Ожидает выгрузки'), ('exported', 'Выгружен'), ('failed', 'Ошибка выгрузки')], default='pending', max_length=20, verbose_name='Статус выгрузки')),
                ('delivery_cost', apps.core.models.MoneyField(decimal_places=2, default=0, max_digits=10, verbose_name='Стоимость доставки')),
                ('delivery_days', models.PositiveIntegerField(blank=True, null=True, verbose_name='Срок доставки (дни)')),
                ('delivery_city', models.CharField(max_length=100, verbose_name='Населенный пункт')),
                ('total_amount', apps.core.models.MoneyField(decimal_places=2, max_digits=10, verbose_name='Сумма товаров')),
                ('total_weight', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Вес (кг)')),
                ('promo_code', models.CharField(blank=True, max_length=50, verbose_name='Промокод')),
                ('discount_amount', apps.core.models.MoneyField(decimal_places=2, default=0, max_digits=10, verbose_name='Сумма скидки')),
                ('final_amount', apps.core.models.MoneyField(decimal_places=2, max_digits=10, verbose_name='Сумма к оплате')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Создано пользователем')),
                ('delivery_address', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.address', verbose_name='Адрес доставки')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Обновлено пользователем')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='Покупатель')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
                'ordering': ['-order_date'],
            },
        ),
        migrations.CreateModel(
            name='OrderLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Количество')),
                ('price', apps.core.models.MoneyField(decimal_places=2, max_digits=10, verbose_name='Цена за единицу')),
                ('total', apps.core.models.MoneyField(decimal_places=2, max_digits=10, verbose_name='Общая стоимость')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='orders.order', verbose_name='Заказ')),
                ('product_variant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.productvariant', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Позиция заказа',
                'verbose_name_plural': 'Позиции заказа',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='OrderStatusTransition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(blank=True, max_length=20, verbose_name='Из статуса')),
                ('to_status', models.CharField(max_length=20, verbose_name='В статус')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата изменения')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Изменено пользователем')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_transitions', to='orders.order', verbose_name='Заказ')),
            ],
            options={
                'verbose_name': 'Переход статуса',
                'verbose_name_plural': 'Переходы статусов',
                'ordering': ['-created_at'],
            },
        ),
    ]
