# Generated by Django 5.2.6 on 2025-10-05 19:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Название статуса')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Код статуса')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('color', models.CharField(default='#6c757d', max_length=7, verbose_name='Цвет статуса')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок сортировки')),
            ],
            options={
                'verbose_name': 'Статус заказа',
                'verbose_name_plural': 'Статусы заказов',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='orders.orderstatus', verbose_name='Статус заказа'),
        ),
        migrations.AlterField(
            model_name='orderstatustransition',
            name='from_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transitions_from', to='orders.orderstatus', verbose_name='Из статуса'),
        ),
        migrations.AlterField(
            model_name='orderstatustransition',
            name='to_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transitions_to', to='orders.orderstatus', verbose_name='В статус'),
        ),
    ]
