# Generated by Django 5.2.6 on 2025-09-23 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('middle_name', models.CharField(blank=True, max_length=100, verbose_name='Отчество')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('country', models.CharField(default='Россия', max_length=100, verbose_name='Страна')),
                ('region', models.CharField(max_length=100, verbose_name='Регион')),
                ('city', models.CharField(max_length=100, verbose_name='Город')),
                ('postal_code', models.CharField(max_length=10, verbose_name='Почтовый индекс')),
                ('street', models.CharField(max_length=200, verbose_name='Улица')),
                ('house', models.CharField(max_length=20, verbose_name='Дом')),
                ('apartment', models.CharField(blank=True, max_length=20, verbose_name='Квартира')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('is_default', models.BooleanField(default=False, verbose_name='По умолчанию')),
                ('cdek_city_code', models.CharField(blank=True, max_length=20, verbose_name='Код города СДЭК')),
                ('cdek_region_code', models.CharField(blank=True, max_length=20, verbose_name='Код региона СДЭК')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Адрес',
                'verbose_name_plural': 'Адреса',
                'ordering': ['-is_default', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OutboxEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('order_created', 'Заказ создан'), ('order_paid', 'Заказ оплачен'), ('order_shipped', 'Заказ отправлен'), ('payment_created', 'Платеж создан'), ('payment_succeeded', 'Платеж успешен'), ('payment_failed', 'Платеж неуспешен')], max_length=50, verbose_name='Тип события')),
                ('aggregate_id', models.CharField(max_length=100, verbose_name='ID агрегата')),
                ('payload', models.JSONField(verbose_name='Данные события')),
                ('status', models.CharField(choices=[('pending', 'Ожидает'), ('processing', 'Обрабатывается'), ('completed', 'Завершено'), ('failed', 'Ошибка')], default='pending', max_length=20, verbose_name='Статус')),
                ('retry_count', models.PositiveIntegerField(default=0, verbose_name='Количество попыток')),
                ('error_message', models.TextField(blank=True, verbose_name='Сообщение об ошибке')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='Обработано')),
            ],
            options={
                'verbose_name': 'Событие',
                'verbose_name_plural': 'События',
                'ordering': ['-created_at'],
            },
        ),
    ]
