# Generated by Django 5.2.6 on 2025-09-29 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'ordering': ['-is_default', '-created_at'], 'verbose_name': 'Адрес доставки', 'verbose_name_plural': 'Адреса доставки'},
        ),
        migrations.AddField(
            model_name='address',
            name='cdek_pvz_code',
            field=models.CharField(blank=True, max_length=20, verbose_name='Код ПВЗ СДЭК'),
        ),
        migrations.AddField(
            model_name='address',
            name='delivery_type',
            field=models.CharField(choices=[('pickup', 'Самовывоз из ПВЗ'), ('courier', 'Доставка курьером')], default='courier', max_length=20, verbose_name='Тип доставки'),
        ),
        migrations.AddField(
            model_name='address',
            name='pvz_address',
            field=models.CharField(blank=True, max_length=300, verbose_name='Адрес ПВЗ'),
        ),
        migrations.AddField(
            model_name='address',
            name='pvz_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='Название ПВЗ'),
        ),
        migrations.AddField(
            model_name='address',
            name='pvz_phone',
            field=models.CharField(blank=True, max_length=50, verbose_name='Телефон ПВЗ'),
        ),
        migrations.AddField(
            model_name='address',
            name='pvz_work_time',
            field=models.CharField(blank=True, max_length=100, verbose_name='Время работы ПВЗ'),
        ),
        migrations.AlterField(
            model_name='address',
            name='comment',
            field=models.TextField(blank=True, verbose_name='Комментарий к доставке'),
        ),
        migrations.AlterField(
            model_name='address',
            name='house',
            field=models.CharField(blank=True, max_length=20, verbose_name='Дом'),
        ),
        migrations.AlterField(
            model_name='address',
            name='postal_code',
            field=models.CharField(blank=True, max_length=10, verbose_name='Почтовый индекс'),
        ),
        migrations.AlterField(
            model_name='address',
            name='region',
            field=models.CharField(blank=True, max_length=100, verbose_name='Регион'),
        ),
        migrations.AlterField(
            model_name='address',
            name='street',
            field=models.CharField(blank=True, max_length=200, verbose_name='Улица'),
        ),
    ]
