# Generated by Django 5.2.6 on 2025-09-29 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='is_featured',
            field=models.BooleanField(default=False, verbose_name='Рекомендуемая'),
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, help_text='Рекомендуемый размер: 400x300px', null=True, upload_to='categories/', verbose_name='Обложка'),
        ),
    ]
