# Generated by Django 5.2.6 on 2025-09-29 12:17

import apps.core.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_carestage_productlabel_producttype_shelflife_volume'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productvariant',
            options={'ordering': ['sort_order', 'volume__sort_order'], 'verbose_name': 'Вариант товара', 'verbose_name_plural': 'Варианты товаров'},
        ),
        migrations.RemoveField(
            model_name='product',
            name='description',
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='base_price',
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='name',
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='sku',
        ),
        migrations.AddField(
            model_name='product',
            name='card_description',
            field=models.TextField(default='', verbose_name='Описание в карточке товара'),
        ),
        migrations.AddField(
            model_name='product',
            name='care_purpose',
            field=models.CharField(choices=[('face', 'Для кожи лица, декольте и рук'), ('eyes', 'Для кожи век'), ('body', 'Для сухих зон на теле (губ, кутикулы и тд.)')], default='face', max_length=100, verbose_name='Для чего'),
        ),
        migrations.AddField(
            model_name='product',
            name='care_stage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='catalog.carestage', verbose_name='Этап ухода'),
        ),
        migrations.AddField(
            model_name='product',
            name='full_description',
            field=models.TextField(default='', verbose_name='Полное описание'),
        ),
        migrations.AddField(
            model_name='product',
            name='hover_image',
            field=models.ImageField(blank=True, null=True, upload_to='products/hover/', verbose_name='Изображение при ховере'),
        ),
        migrations.AddField(
            model_name='product',
            name='label',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.productlabel', verbose_name='Лейбл'),
        ),
        migrations.AddField(
            model_name='product',
            name='label_expires_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Срок действия лейбла'),
        ),
        migrations.AddField(
            model_name='product',
            name='main_image',
            field=models.ImageField(blank=True, null=True, upload_to='products/main/', verbose_name='Основная обложка'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='catalog.producttype', verbose_name='Тип продукта'),
        ),
        migrations.AddField(
            model_name='product',
            name='shelf_life',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='catalog.shelflife', verbose_name='Срок годности'),
        ),
        migrations.AddField(
            model_name='product',
            name='sku',
            field=models.CharField(default='', max_length=50, unique=True, verbose_name='Артикул'),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='discount_price',
            field=apps.core.models.MoneyField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Скидка за данный объем'),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='price',
            field=apps.core.models.MoneyField(decimal_places=2, default=0, max_digits=10, verbose_name='Цена за данный объем'),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='volume',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='catalog.volume', verbose_name='Объем'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Название товара'),
        ),
        migrations.AlterField(
            model_name='product',
            name='short_description',
            field=models.TextField(default='', max_length=500, verbose_name='Короткое описание на странице товара'),
        ),
        migrations.CreateModel(
            name='ProductGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('image', models.ImageField(upload_to='products/gallery/', verbose_name='Изображение')),
                ('alt_text', models.CharField(blank=True, max_length=200, verbose_name='Alt текст')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок сортировки')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='catalog.product')),
            ],
            options={
                'verbose_name': 'Изображение галереи',
                'verbose_name_plural': 'Галерея изображений',
                'ordering': ['sort_order'],
            },
        ),
    ]
