# Generated by Django 5.2.6 on 2025-09-29 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_alter_productvariant_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='care_purpose',
        ),
    ]
