# Generated by Django 5.2.6 on 2025-09-29 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_remove_product_care_purpose'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='action_effect',
            field=models.TextField(default='', verbose_name='Действие и эффект'),
        ),
        migrations.AddField(
            model_name='product',
            name='application_method',
            field=models.TextField(default='', verbose_name='Способ применения'),
        ),
        migrations.AddField(
            model_name='product',
            name='composition',
            field=models.TextField(default='', verbose_name='Состав'),
        ),
        migrations.AddField(
            model_name='product',
            name='important_info',
            field=models.TextField(default='', verbose_name='Важно знать!'),
        ),
        migrations.AddField(
            model_name='product',
            name='miraflores_comment',
            field=models.TextField(default='', verbose_name='Комментарий Miraflores'),
        ),
    ]
