# Generated by Django 5.2.6 on 2025-09-29 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_product_action_effect_product_application_method_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='care_purpose',
            field=models.CharField(choices=[('face', 'Для кожи лица, декольте и рук'), ('eyes', 'Для кожи век'), ('body', 'Для сухих зон на теле (губ, кутикулы и тд.)')], default='face', max_length=100, verbose_name='Для чего'),
        ),
    ]
