# Generated by Django 5.2.6 on 2025-09-29 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_product_care_purpose'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='care_purpose',
            field=models.CharField(blank=True, choices=[('face', 'Для кожи лица, декольте и рук'), ('eyes', 'Для кожи век'), ('body', 'Для сухих зон на теле (губ, кутикулы и тд.)')], default='face', max_length=100, verbose_name='Для чего'),
        ),
    ]
