# Generated by Django 5.2.6 on 2025-09-29 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_alter_product_care_purpose'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productvariant',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='updated_by',
        ),
    ]
