# Generated by Django 5.2.6 on 2025-09-29 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_remove_productvariant_created_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productvariant',
            name='barcode',
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='ean',
        ),
    ]
