# Generated by Django 5.2.6 on 2025-09-29 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_remove_productvariant_barcode_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productvariant',
            options={'ordering': ['sort_order'], 'verbose_name': 'Вариант товара', 'verbose_name_plural': 'Варианты товаров'},
        ),
        migrations.AddField(
            model_name='productvariant',
            name='quantity',
            field=models.PositiveIntegerField(default=1, verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='height',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='мм', max_digits=8, null=True, verbose_name='Высота'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='length',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='мм', max_digits=8, null=True, verbose_name='Длина'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='volume',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='м³', max_digits=8, null=True, verbose_name='Объем'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='кг', max_digits=8, null=True, verbose_name='Вес'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='width',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='мм', max_digits=8, null=True, verbose_name='Ширина'),
        ),
    ]
