# Generated by Django 5.2.6 on 2025-09-29 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_alter_productvariant_options_productvariant_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='currency',
            field=models.CharField(choices=[('RUB', 'Рубли ₽'), ('USD', 'USD'), ('EUR', 'EUR')], default='RUB', max_length=3, verbose_name='Валюта'),
        ),
    ]
