# Generated by Django 5.2.6 on 2025-09-29 12:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0013_productvariant_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='volume_cubic',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='м³', max_digits=8, null=True, verbose_name='Объем'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='volume',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='catalog.volume', verbose_name='Объем'),
        ),
    ]
