# Generated by Django 5.2.6 on 2025-09-29 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0014_productvariant_volume_cubic_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariant',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='г', max_digits=8, null=True, verbose_name='Вес'),
        ),
    ]
