# Generated by Django 5.2.6 on 2025-09-29 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0015_alter_productvariant_weight'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductAttributeValue',
        ),
        migrations.DeleteModel(
            name='AttributeValue',
        ),
        migrations.DeleteModel(
            name='Attribute',
        ),
    ]
