# Generated by Django 5.2.6 on 2025-10-05 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0016_auto_20250929_1603'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['sort_order', 'name'], 'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
    ]
