# Generated by Django 5.2.6 on 2025-10-05 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0017_alter_category_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='sku',
        ),
        migrations.AddField(
            model_name='productvariant',
            name='sku',
            field=models.CharField(default='', max_length=50, verbose_name='Код товара'),
        ),
    ]
