# Generated by Django 5.2.6 on 2025-10-05 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0021_recalculate_volumes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariant',
            name='volume_cubic',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='м³ (рассчитывается автоматически по размерам)', max_digits=8, null=True, verbose_name='Объем'),
        ),
    ]
