# Generated by Django 5.2.6 on 2025-10-05 19:02

import apps.core.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0022_alter_productvariant_volume_cubic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productvariant',
            name='discount_price',
        ),
        migrations.AddField(
            model_name='productvariant',
            name='discount_amount',
            field=apps.core.models.MoneyField(blank=True, decimal_places=2, help_text='Сумма скидки в рублях', max_digits=10, null=True, verbose_name='Сумма скидки'),
        ),
    ]
