# Generated by Django 5.2.6 on 2025-10-05 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0023_remove_productvariant_discount_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productvariant',
            name='discount_amount',
        ),
        migrations.AddField(
            model_name='productvariant',
            name='discount_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Скидка в процентах (например: 20.00)', max_digits=5, null=True, verbose_name='Скидка'),
        ),
    ]
